// Mocks generated by Mockito 5.4.6 from annotations
// in fitflow/test/features/settings/presentation/bloc/sound_settings/sound_settings_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:fitflow/core/failure/failure.dart' as _i5;
import 'package:fitflow/features/settings/domain/entities/sound_settings.dart'
    as _i6;
import 'package:fitflow/features/settings/domain/usecases/get_sound_settings.dart'
    as _i3;
import 'package:fitflow/features/settings/domain/usecases/save_sound_settings.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetSoundSettings].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSoundSettings extends _i1.Mock implements _i3.GetSoundSettings {
  MockGetSoundSettings() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.SoundSettings>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.SoundSettings>>.value(
                  _FakeEither_0<_i5.Failure, _i6.SoundSettings>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.SoundSettings>>);
}

/// A class which mocks [SaveSoundSettings].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveSoundSettings extends _i1.Mock implements _i7.SaveSoundSettings {
  MockSaveSoundSettings() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> call(
    _i6.SoundSettings? settings,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [settings]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i5.Failure, _i2.Unit>(
                this,
                Invocation.method(#call, [settings]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);
}
